version: '3.4'

services:
  dispatcher:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  notifier:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

